// <auto-generated />
using System;
using CloudStaff.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudStaff.DataContext.Migrations
{
    [DbContext(typeof(CloudStaffContext))]
    [Migration("20260611092158_RefactorAllocationsToDateRange")]
    partial class RefactorAllocationsToDateRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudStaff.EntityModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.ClientProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("client_projects", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.HomePool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("home_pools", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsNumber")
                        .IsUnique();

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContractJobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("GcmLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("HomePoolId")
                        .HasColumnType("integer");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SfiaLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("StaffRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsNumber")
                        .IsUnique();

                    b.HasIndex("HomePoolId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StaffRoleId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientProjectId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientProjectId");

                    b.HasIndex("StaffId");

                    b.ToTable("staff_allocations", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("staff_categories", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffPlatform", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("StaffId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("staff_platforms", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomePoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HomePoolId");

                    b.ToTable("staff_roles", (string)null);
                });

            modelBuilder.Entity("CloudStaff.EntityModels.ClientProject", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.HomePool", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.StaffCategory", "Category")
                        .WithMany("HomePools")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Staff", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.HomePool", "HomePool")
                        .WithMany("Staff")
                        .HasForeignKey("HomePoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloudStaff.EntityModels.Manager", "Manager")
                        .WithMany("Staff")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudStaff.EntityModels.StaffRole", "StaffRole")
                        .WithMany("Staff")
                        .HasForeignKey("StaffRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomePool");

                    b.Navigation("Manager");

                    b.Navigation("StaffRole");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffAllocation", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.ClientProject", "ClientProject")
                        .WithMany()
                        .HasForeignKey("ClientProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudStaff.EntityModels.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProject");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffPlatform", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.Platform", "Platform")
                        .WithMany("StaffPlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudStaff.EntityModels.Staff", "Staff")
                        .WithMany("StaffPlatforms")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffRole", b =>
                {
                    b.HasOne("CloudStaff.EntityModels.HomePool", "HomePool")
                        .WithMany("Roles")
                        .HasForeignKey("HomePoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomePool");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.HomePool", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Manager", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Platform", b =>
                {
                    b.Navigation("StaffPlatforms");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.Staff", b =>
                {
                    b.Navigation("StaffPlatforms");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffCategory", b =>
                {
                    b.Navigation("HomePools");
                });

            modelBuilder.Entity("CloudStaff.EntityModels.StaffRole", b =>
                {
                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
